**TASK:** import numpy

In [2]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [4]:
x = np.array([2,4,1])

**TASK:** define (2 x 2) matrix 'A' 


In [14]:
A = np.array([[1,2],[3,4]])

**TASK:** define (2 x 2) matrix 'B'

In [15]:
B = np.array([[1,8],[5,8]])

**TASK:** check the type of 'x'

In [16]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [17]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [18]:
x.shape

(3,)

**TASK:** check the type of 'A'

In [19]:
A.shape

(2, 2)

**TASK:** 

In [20]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

"\nDefine function 'have_same_shape' which checks if two arrays have same shape.\n\nPARAMS:\n    array_1 (numpy.ndarray) - first array\n    array_2 (numpy.ndarray) - second array\nRETURN:\n    True - if arrays have same shape\n    False - if arrays do not have same shape\n\nAlso print 'Arrays must have same shape!' when returning False\n"

In [21]:
def have_same_shape(A,B):
    if A.shape == B.shape:
        return True
    else:
        return False

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [22]:
have_same_shape(A,x)

False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [23]:
have_same_shape(A,B)

True

**TASK:** 

In [ ]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


In [26]:
def matrix_adition(A,B):
    if(have_same_shape(A,B)):
        return A + B
    else:
        return null

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [27]:
matrix_adition(A,B)

array([[ 2, 10],
       [ 8, 12]])

**TASK:** 

In [1]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [39]:
def multiple_matrix_addition(list):
    addition = np.array([])
    for array in list:
        if addition.size == 0:
            addition = array
        else:
            addition = matrix_adition(addition, array)
    return addition
    

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [40]:
multiple_matrix_addition([A,A,B,B])

array([[ 4, 20],
       [16, 24]])

**TASK:** 

In [ ]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [56]:
def can_multiply(A,B):
    if A.shape[1] == B.shape[0]:
        print("({},{})".format(A.shape[1],B.shape[0]))
        return True
    else:
        print("Matrices can not be multiplied.")
        return False

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [57]:
can_multiply(A,B)

(2,2)


True

**TASK:**  define matrix (3 x 2) matrix C

In [58]:
C = np.array([[2,1],[4,8],[4,7]])

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [59]:
can_multiply(A,C)

Matrices can not be multiplied.


False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [60]:
can_multiply(C,A)

(2,2)


True

**TASK:** 

In [61]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

"\nDefine function 'matrix_multiplication' that multiply two numpy.ndarrays\n\nPARAMS:\n   array_a (numpy.ndarray) - first array\n   array_b (numpy.ndarray) - second array\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new A * B array\n    \nDo not forget to check if two matrices can be multiplied.\n\n"

In [62]:
def matrix_multiplication(A,B):
    if can_multiply(A,B):
        return A.dot(B)
    else:
        return False

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [63]:
matrix_multiplication(C,B)

(2,2)


array([[ 7, 24],
       [44, 96],
       [39, 88]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [64]:
matrix_multiplication(A,C)

Matrices can not be multiplied.


False